"""Explain replay failures without deciding whether a proof or audit passes.

Wrappers call these functions only as messages for existing failed assertions.
No result here changes an exit status, expected answer, digest or solver budget.
"""
import json


def identity_failure(path, expected, actual):
    return (
        f'ARTIFACT_IDENTITY_MISMATCH: {path}\n'
        f'Expected SHA-256: {expected}\nActual SHA-256:   {actual}\n'
        'Generated bytes differ from the audited snapshot. A different Yosys '
        'build can cause this even when solver obligations pass. This mismatch '
        'is not itself a proof counterexample; the exact replay has not passed. '
        'Use the recorded toolchain in REPRODUCE.md. Do not replace expected '
        'hashes to bypass the check.'
    )


def stage_failure(stage, code, log_path, checks=None):
    lines = [f'REPLAY_STAGE_FAILED: {stage} exited {code}. See {log_path}.']
    if checks is not None:
        try:
            inputs = json.loads((checks / 'INPUTS.json').read_text())['jobs']
            results = json.loads((checks / 'FINISHED.json').read_text())['jobs']
            if set(inputs) != set(results):
                raise ValueError('missing or extra job results')
            details = []
            for name, row in sorted(results.items()):
                if row['passed'] is True:
                    continue
                expected, answers = inputs[name]['expected'], row['answers']
                log = (checks / name / 'solver.log').read_text()
                if row['exit'] != 0 or row['source_unchanged'] is not True or '(error ' in log:
                    status = 'TOOL_OR_CHECK_ERROR'
                elif (len(answers) == len(expected) and 'unknown' in answers
                      and all(a == e or a == 'unknown' for a, e in zip(answers, expected))):
                    status = 'SOLVER_INCONCLUSIVE (not proved)'
                elif answers != expected:
                    status = 'UNEXPECTED_SOLVER_ANSWER'
                else:
                    status = 'TOOL_OR_CHECK_ERROR'
                details.append(f'{name}: {status}; expected={expected!r}, '
                               f'observed={answers!r}. See {checks / name / "solver.log"}.')
            lines.extend(details)
        except (OSError, ValueError, KeyError, TypeError, AttributeError) as error:
            lines.append(f'Detailed query diagnostics unavailable ({type(error).__name__}); '
                         'inspect the stage log for the tool or check error.')
    lines.append('This replay has not passed. Unknowns and timeouts are not proofs. '
                 'Consult REPRODUCE.md#formal-toolchain-and-replay-results; '
                 'do not weaken the required checks.')
    return '\n'.join(lines)
